### ISSUE TITLE
Doesnt this have dedicated input layer?

### ISSUE THREAD

**Issue by ErenBalatkan** [fabiotosi92/monoResMatch-Tensorflow#5]
I am trying to use this project for estimating depth of vehicles under traffic, but im failing to see how i am supposed to give input frames to this network, from inspecting your code, you guys seem to be giving inputs to network during network creation and not via placeholders and feed dicts

![image](https://user-images.githubusercontent.com/17107724/62031782-d5475500-b1f0-11e9-8031-bf80ad30a570.png)

**Comment by mattpoggi** [comment]
Hi @Navhkrin ,
the input node self.left given to the network is directly fed by the dataloader. You can replace it with a placeholder as well, but this is usually slower.
