### ISSUE TITLE
Details of generating SGM proxy labels

### ISSUE THREAD

**Issue by ViktorLiang** [fabiotosi92/monoResMatch-Tensorflow#9]
Thanks for sharing your excellent work. 
Aiming at training the model locally, I compiled rSGM as you mentioned but have no idea of how to use it to gen proxy labels. Could you tell more details about generating SGM proxy labels? Thanks in advance.

**Comment by mattpoggi** [comment]
Dear @YuanLeung ,
we used the code available here https://github.com/ivankreso/stereo-vision/tree/master/reconstruction/base/rSGM to generate the proxy labels.

You can also use the OpenCV SGM implementation, maybe followed by a simple speckle filter, to obtain similar results. Here a few lines in python to obtain some cheap labels:

`import cv2`
`sgm = cv2.StereoSGBM(0,192,1)`
`disparity = sgm.compute(left,right)/16.`
`cv2.filterSpeckles(disparity , 0, 1000, 16)`
